# Generated by Django 5.1.4 on 2024-12-28 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('date_encountered', models.DateField(auto_now_add=True)),
                ('captured', models.BooleanField()),
                ('description', models.TextField(default='Unkown', validators=[django.core.validators.MinLengthValidator(25), django.core.validators.MaxLengthValidator(150)])),
            ],
        ),
    ]
