# Generated by Django 5.1.4 on 2024-12-28 15:42

import pokemon_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_app', '0001_initial'),
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(to='move_app.move'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=255, validators=[pokemon_app.validators.validate_name]),
        ),
    ]
