# Generated by Django 5.1.4 on 2025-01-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0003_pokemon_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='captured',
            field=models.BooleanField(default=False),
        ),
    ]
